# Generated by Django 6.0 on 2025-12-15 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoxOfficeRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='순위')),
                ('genre_code', models.CharField(max_length=10, verbose_name='장르코드')),
                ('ranking_date', models.DateField(verbose_name='랭킹 기준일')),
                ('period_type', models.CharField(choices=[('day', '일간'), ('week', '주간'), ('month', '월간')], default='week', max_length=10, verbose_name='기간유형')),
                ('area', models.CharField(blank=True, max_length=50, null=True, verbose_name='지역')),
                ('seat_count', models.IntegerField(default=0, verbose_name='좌석수')),
                ('performance_count', models.IntegerField(default=0, verbose_name='공연횟수')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='수집일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '박스오피스 랭킹',
                'verbose_name_plural': '박스오피스 랭킹 목록',
                'ordering': ['ranking_date', 'genre_code', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('mt20id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='공연 ID')),
                ('prfnm', models.CharField(max_length=255, verbose_name='공연명')),
                ('prfpdfrom', models.DateField(blank=True, null=True, verbose_name='공연시작일')),
                ('prfpdto', models.DateField(blank=True, null=True, verbose_name='공연종료일')),
                ('fcltynm', models.CharField(blank=True, max_length=100, null=True, verbose_name='공연시설명')),
                ('poster', models.URLField(blank=True, max_length=2048, null=True, verbose_name='포스터URL')),
                ('area', models.CharField(blank=True, max_length=50, null=True, verbose_name='지역')),
                ('genrenm', models.CharField(blank=True, max_length=50, null=True, verbose_name='장르')),
                ('prfstate', models.CharField(blank=True, max_length=50, null=True, verbose_name='공연상태')),
                ('openrun', models.CharField(blank=True, max_length=5, null=True)),
                ('rnum', models.CharField(blank=True, null=True)),
                ('cast_search_text', models.TextField(blank=True, null=True, verbose_name='검색용 출연진 텍스트')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='이미지 URL')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='수집일시')),
            ],
            options={
                'verbose_name': '공연 소개 이미지',
                'verbose_name_plural': '공연 소개 이미지 목록',
                'ordering': ['performance', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceDetail',
            fields=[
                ('performance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detail', serialize=False, to='performances.performance', verbose_name='공연')),
                ('prfcast', models.TextField(blank=True, verbose_name='출연진')),
                ('prfcrew', models.TextField(blank=True, verbose_name='제작진')),
                ('prfruntime', models.CharField(blank=True, max_length=50, verbose_name='공연시간')),
                ('prfage', models.CharField(blank=True, max_length=50, verbose_name='관람연령')),
                ('entrpsnm', models.CharField(blank=True, max_length=200, verbose_name='제작사')),
                ('pcseguidance', models.TextField(blank=True, verbose_name='티켓가격')),
                ('sty', models.TextField(blank=True, verbose_name='줄거리')),
                ('dtguidance', models.TextField(blank=True, verbose_name='공연시간안내')),
                ('relates', models.JSONField(blank=True, default=list, verbose_name='예매처')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='수집일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '공연 상세 정보',
                'verbose_name_plural': '공연 상세 정보 목록',
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('performance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='metric', serialize=False, to='performances.performance', verbose_name='공연')),
                ('score_popularity', models.FloatField(default=0.0, verbose_name='대중성 점수')),
                ('score_recency', models.FloatField(default=0.0, verbose_name='최신성 점수')),
                ('similar_performances', models.JSONField(blank=True, default=list, verbose_name='유사 공연 ID 목록')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='통계 갱신일시')),
            ],
            options={
                'verbose_name': '공연 추천 지표',
                'verbose_name_plural': '공연 추천 지표 목록',
            },
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['prfstate'], name='performance_prfstat_691a22_idx'),
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['genrenm'], name='performance_genrenm_f5138b_idx'),
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['prfpdfrom', 'prfpdto'], name='performance_prfpdfr_a031cf_idx'),
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['area'], name='performance_area_85387a_idx'),
        ),
        migrations.AddField(
            model_name='boxofficeranking',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_office_rankings', to='performances.performance', verbose_name='공연'),
        ),
        migrations.AddField(
            model_name='performanceimage',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intro_images', to='performances.performance', verbose_name='공연'),
        ),
        migrations.AddIndex(
            model_name='performancemetric',
            index=models.Index(fields=['-score_popularity'], name='performance_score_p_fe4906_idx'),
        ),
        migrations.AddIndex(
            model_name='performancemetric',
            index=models.Index(fields=['-score_recency'], name='performance_score_r_582fba_idx'),
        ),
        migrations.AddIndex(
            model_name='boxofficeranking',
            index=models.Index(fields=['genre_code', 'ranking_date', 'rank'], name='performance_genre_c_560df9_idx'),
        ),
        migrations.AddIndex(
            model_name='boxofficeranking',
            index=models.Index(fields=['ranking_date', '-collected_at'], name='performance_ranking_fea9c2_idx'),
        ),
        migrations.AddIndex(
            model_name='boxofficeranking',
            index=models.Index(fields=['performance', 'ranking_date'], name='performance_perform_218139_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='boxofficeranking',
            unique_together={('ranking_date', 'genre_code', 'rank', 'period_type')},
        ),
        migrations.AddIndex(
            model_name='performanceimage',
            index=models.Index(fields=['performance', 'order'], name='performance_perform_4702e8_idx'),
        ),
    ]
