# Generated by Django 6.0 on 2025-12-17 06:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='favorite_performances', to=settings.AUTH_USER_MODEL, verbose_name='찜한 사용자'),
        ),
    ]
