# Generated by Django 5.2.8 on 2025-12-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0002_performance_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='embedding_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='임베딩 갱신일시'),
        ),
        migrations.AddField(
            model_name='performance',
            name='embedding_vector',
            field=models.JSONField(blank=True, help_text='OpenAI text-embedding-3-small 벡터 (1536차원)', null=True, verbose_name='임베딩 벡터'),
        ),
    ]
