# Generated by Django 5.2.8 on 2025-12-20 13:14

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def migrate_embeddings_to_new_table(apps, schema_editor):
    """기존 Performance의 임베딩 데이터를 PerformanceEmbedding으로 이관"""
    Performance = apps.get_model('performances', 'Performance')
    PerformanceEmbedding = apps.get_model('performances', 'PerformanceEmbedding')

    # 임베딩이 있는 공연들만 조회
    performances_with_embeddings = Performance.objects.filter(
        embedding_vector__isnull=False
    )

    # PerformanceEmbedding 레코드 생성
    embeddings_to_create = []
    for perf in performances_with_embeddings:
        embeddings_to_create.append(
            PerformanceEmbedding(
                performance_id=perf.mt20id,
                vector=perf.embedding_vector,
                # created_at은 auto_now_add이므로 자동 생성됨
                # updated_at은 기존 값 사용 (없으면 현재 시간)
            )
        )
        # updated_at을 수동으로 설정하기 위해 객체 생성 후 설정
        if perf.embedding_updated_at:
            embeddings_to_create[-1].updated_at = perf.embedding_updated_at

    # bulk_create로 한 번에 삽입
    if embeddings_to_create:
        # created_at은 bulk_create에서 자동 설정 안 되므로 수동 설정
        now = timezone.now()
        for emb in embeddings_to_create:
            emb.created_at = emb.updated_at or now
            if not emb.updated_at:
                emb.updated_at = now

        PerformanceEmbedding.objects.bulk_create(embeddings_to_create, batch_size=500)
        print(f"Successfully migrated {len(embeddings_to_create)} embeddings to new table")


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0003_performance_embedding_updated_at_and_more'),
    ]

    operations = [
        # 1. 먼저 새 테이블 생성
        migrations.CreateModel(
            name='PerformanceEmbedding',
            fields=[
                ('performance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='embedding', serialize=False, to='performances.performance', verbose_name='공연')),
                ('vector', models.JSONField(help_text='OpenAI text-embedding-3-small (1536차원)', verbose_name='임베딩 벡터')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='갱신일시')),
            ],
            options={
                'verbose_name': '공연 임베딩',
                'verbose_name_plural': '공연 임베딩 목록',
                'db_table': 'performance_embeddings',
                'indexes': [models.Index(fields=['updated_at'], name='performance_updated_3f6992_idx')],
            },
        ),
        # 2. 데이터 이관
        migrations.RunPython(migrate_embeddings_to_new_table, migrations.RunPython.noop),
        # 3. 기존 필드 제거
        migrations.RemoveField(
            model_name='performance',
            name='embedding_updated_at',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='embedding_vector',
        ),
    ]
