# Generated by Django 5.2.8 on 2025-12-21 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performances", "0004_remove_performance_embedding_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="YouTubeVideoCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cache_key",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="캐시 키",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("FOUND", "발견"), ("NONE", "없음")],
                        max_length=10,
                        verbose_name="상태",
                    ),
                ),
                (
                    "video_data",
                    models.JSONField(
                        help_text="List of videos or single video object",
                        verbose_name="영상 데이터",
                    ),
                ),
                (
                    "fallback_data",
                    models.JSONField(blank=True, null=True, verbose_name="대체 데이터"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "performance",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="youtube_cache",
                        to="performances.performance",
                        verbose_name="공연",
                    ),
                ),
            ],
            options={
                "verbose_name": "YouTube 영상 캐시",
                "verbose_name_plural": "YouTube 영상 캐시 목록",
                "indexes": [
                    models.Index(
                        fields=["cache_key"], name="performance_cache_k_44b8f3_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="performance_updated_e07418_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("performance__isnull", False),
                            ("cache_key__isnull", False),
                            _connector="OR",
                        ),
                        name="either_performance_or_cache_key",
                    )
                ],
            },
        ),
    ]
