# Generated by Django 6.0 on 2025-12-17 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_add_user_extended_fields'),
        ('performances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationCache',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='recommendation_cache', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('top_n_list', models.JSONField(blank=True, default=list, verbose_name='추천 목록')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='갱신 일시')),
            ],
            options={
                'verbose_name': '추천 결과 캐시',
                'verbose_name_plural': '추천 결과 캐시 목록',
            },
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('view', '조회'), ('like', '찜하기'), ('search', '검색')], max_length=10, verbose_name='행동 유형')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='발생 시각')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_logs', to='performances.performance', verbose_name='공연')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_logs', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 행동 로그',
                'verbose_name_plural': '사용자 행동 로그 목록',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='recommendat_user_id_c90a9b_idx'), models.Index(fields=['performance', '-timestamp'], name='recommendat_perform_8f481b_idx'), models.Index(fields=['action_type', '-timestamp'], name='recommendat_action__88db3c_idx')],
            },
        ),
    ]
