# Generated by Django 5.2.8 on 2025-12-15 10:42

from django.db import migrations


def mark_as_applied(apps, schema_editor):
    """
    This migration marks the manual database changes as applied.
    The actual columns were already added via SQL ALTER TABLE commands
    to preserve existing data.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(mark_as_applied, reverse_code=migrations.RunPython.noop),
    ]
