# Generated by Django 5.2.8 on 2025-12-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_user_extended_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='region_dong',
        ),
        migrations.RemoveField(
            model_name='user',
            name='region_gu',
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='거주 지역 (광역시/도)'),
        ),
    ]
