# Generated by Django 5.2.8 on 2025-12-21 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_user_region_dong_remove_user_region_gu_and_more"),
        ("performances", "0005_youtubevideocache"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="preference",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
                (
                    "preference_vector",
                    models.JSONField(
                        help_text="1536차원 사용자 선호 벡터 (normalized)",
                        verbose_name="선호도 벡터",
                    ),
                ),
                (
                    "signal_count",
                    models.IntegerField(
                        default=0,
                        help_text="온보딩 시 선택한 공연 개수",
                        verbose_name="시그널 개수",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "사용자 선호도",
                "verbose_name_plural": "사용자 선호도 목록",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="has_onboarded",
            field=models.BooleanField(default=False, verbose_name="온보딩 완료 여부"),
        ),
        migrations.AddField(
            model_name="user",
            name="onboarded_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="온보딩 완료 시각"
            ),
        ),
        migrations.CreateModel(
            name="UserPerformanceSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "signal",
                    models.FloatField(
                        choices=[
                            (1.5, "보고싶어요"),
                            (0.0, "모르겠어요"),
                            (-1.0, "안보고싶어요"),
                        ],
                        verbose_name="반응",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_signals",
                        to="performances.performance",
                        verbose_name="공연",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_signals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 공연 시그널",
                "verbose_name_plural": "사용자 공연 시그널 목록",
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="accounts_us_user_id_da1fe1_idx",
                    )
                ],
                "unique_together": {("user", "performance")},
            },
        ),
    ]
