# Generated by Django 5.2.8 on 2025-12-21 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0004_userpreference_user_has_onboarded_user_onboarded_at_and_more",
        ),
        ("performances", "0005_youtubevideocache"),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchedPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "watched_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="관람 등록 시각"
                    ),
                ),
                (
                    "rating",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="1~5점 별점 (선택사항)",
                        null=True,
                        verbose_name="별점 (1-5)",
                    ),
                ),
                (
                    "performance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watched_by_users",
                        to="performances.performance",
                        verbose_name="공연",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watched_performances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "관람한 공연",
                "verbose_name_plural": "관람한 공연 목록",
                "ordering": ["-watched_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "watched_at"],
                        name="accounts_wa_user_id_f1df97_idx",
                    ),
                    models.Index(
                        fields=["-watched_at"], name="accounts_wa_watched_77ca66_idx"
                    ),
                ],
                "unique_together": {("user", "performance")},
            },
        ),
    ]
