# Generated by Django 5.2 on 2025-12-22 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
        ("performances", "0005_youtubevideocache"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="board_type",
            field=models.CharField(
                choices=[("PERFORMANCE", "공연글"), ("GENERAL", "일반글")],
                default="PERFORMANCE",
                max_length=20,
                verbose_name="게시판 타입",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[
                    ("REVIEW", "후기"),
                    ("EXPECTATION", "기대평"),
                    ("QNA", "질문"),
                    ("FREE", "자유게시판"),
                    ("INFO", "정보공유"),
                ],
                default="REVIEW",
                max_length=20,
                verbose_name="카테고리",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="performance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="performances.performance",
                verbose_name="관련 공연",
            ),
        ),
    ]
